---
- hosts: webserver
  remote_user: ubuntu
  become: true
  vars_files:
    - group_vars/secrets.yml
  roles:
    - geerlingguy.nginx
    - role: geerlingguy.postgresql
      become: true
    - webapp
