---
domain_name: "{{ inventory_hostname }}"
letsencrypt_email: c.hyde@qcif.edu.au

gunicorn:
  web_workers: 4

postgresql_locales:
  - 'en_US.UTF-8'

postgresql_databases:
  - name: webapp
    port: 5432

postgresql_users:
  - name: webapp
    password: secret
    db: webapp

postgres_users_no_log: false
